### ISSUE TITLE
This doesnt work

### ISSUE THREAD

**Issue by gap41** [MindChirp/infoScreen#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows (10,8.1,8,7)

**Additional context**

**Comment by frikkbol** [comment]
Wut

**Comment by gap41** [comment]
This doesnt work

**Comment by frikkbol** [comment]
hæ

**Comment by gap41** [comment]
This does not work
